language: r
cache: packages
sudo: false
warnings_are_errors: false
git:
  depth: false
install:
  - Rscript install-packages.R
  
script:
  - Rscript testthat.R
  
notifications:
  slack: weecology:8l6yh0T3L0cYXPuJ4CiYwhCo
  
after_success:
slack:
    on_success: always
    on_failure: always
